[project]
name = "codenames-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fasttext>=0.9.3",
    "gensim>=4.4.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pytest>=9.1.1",
]

[tool.black]
line-length = 100
target-version = ['py313']
